export const MARQUEE_ITEMS = [
  "Video Interviews",
  "AI Scoring",
  "Assessments",
  "Job Forms",
  "Resume Analyser",
  "Resume Editor",
  "Talent Pool",
  "WhatsApp Messaging",
  "Team Roles",
  "Reports",
];

export const TOUR_VIEWS = [
  "pipeline",
  "candidates",
  "jobs",
  "interviews",
  "offers",
  "people",
  "reports",
] as const;

export type TourView = (typeof TOUR_VIEWS)[number];

export const MODULES = [
  {
    id: "interviews",
    num: "01",
    title: "Interviews",
    subtitle: "One-way video, on their schedule",
    kicker: "One-way video interviews",
    heading: "Screen a hundred people without booking a single call",
    body: "Build a structured set of questions, set a time limit per answer, then send one link. Candidates record whenever suits them — your team reviews, scores and shortlists together afterwards.",
    stat: "62%",
    statLabel: "faster time‑to‑hire",
    items: [
      "Question templates or fully custom sets",
      "Per-question timing, retakes and thinking time",
      "Intro and closing videos carrying your branding",
      "Bulk invites by CSV, with automatic reminders",
      "Team ratings, comments and shared shortlists",
      "Share a candidate externally with a secure link",
    ],
  },
  {
    id: "assessments",
    num: "02",
    title: "Assessments",
    subtitle: "Test the skill, not the CV",
    kicker: "Skills assessments",
    heading: "Find out who can actually do the work",
    body: "Send a role-relevant test before the first conversation. Everything is scored automatically and lands on the same candidate record as their application, interview and notes.",
    stat: "3×",
    statLabel: "fewer unqualified interviews",
    items: [
      "Question bank organised into your own categories",
      "Custom questions with your own correct answers",
      "Timed sections, graded automatically",
      "Set a pass mark and see who clears it",
      "Review each candidate's full breakdown, question by question",
      "Single or bulk invites with secure test links",
    ],
  },
  {
    id: "forms",
    num: "03",
    title: "Job Forms",
    subtitle: "Ask exactly what you need",
    kicker: "Application forms",
    heading: "Collect the right details the first time",
    body: "Build an application form per role with the questions that actually matter, then let knock-out answers filter the obvious no’s out before anybody spends time reading them.",
    stat: "40%",
    statLabel: "less manual screening",
    items: [
      "Drag-and-drop form builder",
      "Knock-out questions that filter automatically",
      "File uploads, portfolios and links",
      "Conditional fields that change per role",
      "Every submission lands in one filtered applicant list",
      "Publish as a public application page for the role",
    ],
  },
  {
    id: "analyser",
    num: "04",
    title: "Resume Analyser",
    subtitle: "Hundreds of CVs, one pass",
    kicker: "Bulk resume analysis",
    heading: "Read the whole pile in the time one takes",
    body: "Drop in a folder of CVs and get every one parsed, matched against the role and ranked — with the reasoning shown next to each score, so you can disagree with it where it’s wrong.",
    stat: "50",
    statLabel: "resumes per batch",
    items: [
      "Upload up to 50 resumes in one batch",
      "Scored against your actual job description",
      "Live progress tracker while the batch runs",
      "The reasoning behind every score",
      "Extracted skills, experience and contact details",
      "Sort, filter and export the ranked shortlist",
    ],
  },
  {
    id: "editor",
    num: "05",
    title: "Resume Editor",
    subtitle: "Clean, consistent, on brand",
    kicker: "Resume editor",
    heading: "Send a CV that looks like it came from you",
    body: "Bulk-import raw CVs and every section comes out structured and editable — reformat into your own template, straighten out the layout and export a clean file, without retyping a single line.",
    stat: "Bulk",
    statLabel: "import, one shared template",
    items: [
      "Your template, your branding",
      "Automatic extraction into clean, editable sections",
      "Inline editing of any section",
      "Reorder, merge or hide sections",
      "Live preview before you export",
      "Share the finished CV via a secure link",
    ],
  },
] as const;

export type PlanFeature = { value?: string | number; label: string };

export type Plan = {
  name: string;
  blurb: string;
  monthly: string;
  yearly: string;
  yearlyBilled?: string;
  periodMonthly: string;
  periodYearly: string;
  cta: string;
  featured?: boolean;
  features: PlanFeature[];
};

const SHARED = [
  { label: "Unlimited team seats on paid plans" },
  { label: "Custom branding & email templates" },
  { label: "Analytics, exports & webhooks" },
];

export const PLANS: Plan[] = [
  {
    name: "Free",
    blurb: "Free plan for getting started with basic recruiting features.",
    monthly: "Free",
    yearly: "Free",
    periodMonthly: "forever",
    periodYearly: "forever",
    cta: "Get started free",
    features: [
      { value: 1, label: "users" },
      { value: 3, label: "active job forms" },
      { value: 500, label: "candidates" },
      { value: 5, label: "video interviews" },
      { value: 5, label: "assessments" },
      { value: 20, label: "bulk resume analyzer" },
      { value: 10, label: "bulk resume editor" },
      { value: 25, label: "ai candidate matching" },
      { value: 3, label: "ai requirements" },
      { value: 1, label: "ai hiring flow preview" },
      { value: 1, label: "ai match score" },
      { value: 1, label: "candidate shortlisting" },
      { value: 1, label: "basic hiring pipeline" },
      { value: 0, label: "team collaboration" },
      ...SHARED,
    ],
  },
  {
    name: "Starter",
    blurb: "Starter plan for small recruiting teams.",
    monthly: "$29.00",
    yearly: "$24.17",
    yearlyBilled: "Billed $290.00 annually",
    periodMonthly: "/month",
    periodYearly: "/month",
    cta: "Start 14-day free trial",
    features: [
      { value: 3, label: "users" },
      { value: 10, label: "active job forms" },
      { value: 3000, label: "candidates" },
      { value: 30, label: "video interviews" },
      { value: 30, label: "assessments" },
      { value: 200, label: "bulk resume analyzer" },
      { value: 100, label: "bulk resume editor" },
      { value: 250, label: "ai candidate matching" },
      { value: 10, label: "ai requirements" },
      { value: 1, label: "ai hiring flow preview" },
      { value: 1, label: "ai match score" },
      { value: 1, label: "candidate shortlisting" },
      { value: 1, label: "basic hiring pipeline" },
      { value: 1, label: "team collaboration" },
      ...SHARED,
    ],
  },
  {
    name: "Professional",
    blurb: "Manage Interview , assessment and bonus hiring features",
    monthly: "$20.00",
    yearly: "$16.60",
    yearlyBilled: "Billed $199.20 annually",
    periodMonthly: "/month",
    periodYearly: "/month",
    cta: "Start 14-day free trial",
    features: [
      { value: 10, label: "interviews" },
      { value: 10, label: "assessments" },
      { value: 500, label: "interview invitations" },
      { value: 500, label: "assessment invitations" },
      { value: 5, label: "job forms" },
      ...SHARED,
    ],
  },
  {
    name: "Professional",
    blurb: "Professional plan for growing recruiting teams.",
    monthly: "$79.00",
    yearly: "$65.83",
    yearlyBilled: "Billed $790.00 annually",
    periodMonthly: "/month",
    periodYearly: "/month",
    cta: "Start 14-day free trial",
    featured: true,
    features: [
      { value: 10, label: "users" },
      { value: 30, label: "active job forms" },
      { value: 15000, label: "candidates" },
      { value: 150, label: "video interviews" },
      { value: 150, label: "assessments" },
      { value: 1000, label: "bulk resume analyzer" },
      { value: 500, label: "bulk resume editor" },
      { value: 2000, label: "ai candidate matching" },
      { value: 30, label: "ai requirements" },
      { value: 1, label: "ai hiring flow preview" },
      { value: 1, label: "ai match score" },
      { value: 1, label: "candidate shortlisting" },
      { value: 1, label: "basic hiring pipeline" },
      { value: 1, label: "team collaboration" },
      ...SHARED,
    ],
  },
  {
    name: "pro",
    blurb: "Pro Plan Include All Access",
    monthly: "$100.00",
    yearly: "$1.00",
    yearlyBilled: "Billed $12.00 annually",
    periodMonthly: "/month",
    periodYearly: "/month",
    cta: "Start 14-day free trial",
    features: [
      { value: 100, label: "interviews" },
      { value: 100, label: "assessments" },
      { value: 1000, label: "interview invitations" },
      { value: 1000, label: "assessment invitations" },
      { value: 100, label: "job forms" },
      { value: 1000, label: "resume analyses" },
      { value: 1000, label: "resume editor" },
      ...SHARED,
    ],
  },
  {
    name: "Business",
    blurb: "Business plan for larger recruiting teams with higher usage limits.",
    monthly: "$149.00",
    yearly: "$124.17",
    yearlyBilled: "Billed $1490.00 annually",
    periodMonthly: "/month",
    periodYearly: "/month",
    cta: "Start 14-day free trial",
    features: [
      { value: 25, label: "users" },
      { value: 100, label: "active job forms" },
      { value: 50000, label: "candidates" },
      { value: 500, label: "video interviews" },
      { value: 500, label: "assessments" },
      { value: 5000, label: "bulk resume analyzer" },
      { value: 2500, label: "bulk resume editor" },
      { value: 10000, label: "ai candidate matching" },
      { value: 100, label: "ai requirements" },
      { value: 1, label: "ai hiring flow preview" },
      { value: 1, label: "ai match score" },
      { value: 1, label: "candidate shortlisting" },
      { value: 1, label: "basic hiring pipeline" },
      { value: 1, label: "team collaboration" },
      ...SHARED,
    ],
  },
];
